version: '3'

services:
  teamtalk:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FILE_NAME: "teamtalk-v5.17-ubuntu22-x86_64"
        URL: "https://bearware.dk/teamtalk/v5.17/teamtalk-v5.17-ubuntu22-x86_64.tgz"
    container_name: ttda
    restart: on-failure
    ports:
      - "10333:10333"
      - "10333:10333/udp"
    volumes:
      - /root/repo/comTT:/server/data
    networks:
      - teamtalk-net

networks:
  teamtalk-net:
    driver: bridge
